### ISSUE TITLE
能否支持一下 多个流程的结果合并为一个数组传递给另外一个流程

### ISSUE THREAD

**Issue by 836145715** [oomol-lab/ovm-desktop#15]
![Image](https://github.com/user-attachments/assets/4650730a-12e8-485c-996a-26b67884c937)

例如这样子，我想让 多个节点返回一个 function 合并为一个 func数组传递给另外一个流程，但是我测试发现不是预想的样子，他变成了两个流程 func_test 执行了两次。 想实现类似 openai的 function call 功能，将区块变为工具提供给大模型调用

**Comment by leavesster** [comment]
我们倾向于保持简单的连线触发逻辑 ———— 一个 node （func_test#3）的 input 端口满了就跑。单个输入点，有一个就认为这个点满了，后续会排队（这样 input 和 output 类型校验很简单）。这个逻辑是无法满足你的需求。

---

不过这个需求，可以手动创建一个专门用来 merge 的 script node 来实现。q

<img width="1461" alt="Image" src="https://github.com/user-attachments/assets/4420192d-073b-49a9-bc80-e9d391c56de2" />

```js
import type { Context } from "@oomol/types/oocana";

//#region generated meta
type Inputs = {
  input: string;
  input1: string;
}
type Outputs = {
  output: string[];
}
//#endregion

export default async function(
  params: Inputs,
  context: Context<Inputs, Outputs>
): Promise<Outputs> {


  const list = [];

  for (const value of Object.values(params)) {

    list.push(value);
  }

  return { output: list };
};

```

这个代码可以给任意多个handle 进行合并。

**Comment by crimx** [comment]
多个输出连到一个输入中我们采取的是队列的方式依次执行，这样避免了连一根线与连多根线时下游类型不一样的问题。

对于收集所有输入再一次过给到下游这个情况我们设计的时候已经考虑的，后续会以另外的机制支持。目前折中的方式如楼上的例子，可以利用一个中间的小脚本，通过增加输入接口来实现合并效果。

<details>
<summary>图示的 flow.oo.yaml 文件</summary>

```yaml
nodes:
  - task:
      ui:
        default_width: 450
      inputs_def:
        []
      outputs_def:
        - handle: function
          description: Output
          json_schema:
            type: string
      executor:
        name: python
        options:
          entry: scriptlets/+python#4.py
    title: function1
    icon: ":logos:python:"
    node_id: +python#4
  - node_id: +python#5
    node_type: task_node
    title: "function2"
    icon: ":logos:python:"
    task:
      ui:
        default_width: 450
      inputs_def:
        []
      outputs_def:
        - handle: function
          description: Output
          json_schema:
            type: string
      executor:
        name: python
        options:
          entry: scriptlets/+python#5.py
          spawn: false
  - task:
      ui:
        default_width: 450
      inputs_def:
        - handle: input
          description: Input
          json_schema:
            type: string
          nullable: false
        - handle: input2
          json_schema:
            type: string
      outputs_def:
        - handle: functions
          description: Output
          json_schema:
            type: array
            items:
              type: string
          nullable: false
      executor:
        name: python
        options:
          entry: scriptlets/+python#6.py
    title: join functions
    icon: ":logos:python:"
    node_id: +python#6
    inputs_from:
      - handle: input
        from_node:
          - node_id: +python#4
            output_handle: function
      - handle: input2
        from_node:
          - node_id: +python#5
            output_handle: function
  - task:
      ui:
        default_width: 450
      inputs_def:
        - handle: functions
          description: Input
          json_schema:
            type: array
            items:
              type: string
      outputs_def:
        - handle: output
          json_schema:
            type: string
      executor:
        name: python
        options:
          entry: scriptlets/+python#7.py
    title: "Python #7"
    icon: ":logos:python:"
    node_id: +python#7
    inputs_from:
      - handle: functions
        from_node:
          - node_id: +python#6
            output_handle: functions

```

</details>

<img width="1698" alt="Image" src="https://github.com/user-attachments/assets/2657de88-a853-4120-a1d0-e414c305222e" />
